[package]
name = "influxdb-csv-cleaner"
version = "0.1.0"
authors = ["Nguyễn Hồng Quân <ng.hong.quan@gmail.com>"]
publish = false
homepage = "http://agriconnect.vn"

[dependencies]
clap = "2"
chrono = "0.3"
chrono-tz = "0.3"
