[package]
name = "influxdb-csv-cleaner"
version = "0.2.0"
authors = ["Nguyễn Hồng Quân <ng.hong.quan@gmail.com>"]
publish = false
homepage = "http://agriconnect.vn"

[dependencies]
clap = "2"
chrono = "0.4"
human-panic = "0.4"
